name: BonBon Flask to AWS EC2

on:
  push:
    branches: [ main ]

env:
  PROJECT_NAME: bonbon-ml
  BUCKET_NAME: bonbon-ml-bucket
  CODE_DEPLOY_APP_NAME: bonbon-dev
  DEPLOYMENT_GROUP_NAME: bonbon-ml-dev
  AWS_REGION: ap-northeast-2

  # SECRET_KEY: ${{ secrets.SECRET_KEY }}
  
  # FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r venus/requirements.txt

      # - name: Create .env file
      #   run: |
      #     echo "MONGO_USER=${{ secrets.MONGO_USER }}" > .env
      #     echo "MONGO_PASS=${{ secrets.MONGO_PASS }}" >> .env
      #     echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
      #     echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env


      - name: Make Zip File
        run: |
          . venv/bin/activate
          zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      # AWS 자격증명 구성 및 AWS CLI 설치
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY_ID}}
          aws-region: ${{env.AWS_REGION}}

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip


      - name: Code Deploy To EC2 instance
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$BUCKET_NAME,key=$PROJECT_NAME/$GITHUB_SHA.zip,bundleType=zip

